---
# All available Hugo versions are listed here:
# https://gitlab.com/pages/hugo/container_registry
image: registry.gitlab.com/pages/hugo:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

hugo:
  before_script:
    - apk add asciidoctor git
  script: hugo
  artifacts:
    paths:
      - public
